import { ApplicationConfig, ErrorHandler, importProvidersFrom, LOCALE_ID, provideBrowserGlobalErrorListeners } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import localeNl from '@angular/common/locales/nl';
import { HttpBackend, provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import { ColorPickerModule } from '@iplab/ngx-color-picker';
import {
  CircleAlert,
  ArrowLeft,
  ArrowLeftRight,
  BookOpen,
  Briefcase,
  Brush,
  Building,
  Calendar,
  CalendarCheck,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  Clock,
  Download,
  Droplet,
  Eraser,
  Eye,
  EyeOff,
  Flame,
  FileText,
  GripVertical,
  Globe,
  Hammer,
  HardHat,
  Heart,
  House,
  Image,
  Inbox,
  LayoutDashboard,
  Lightbulb,
  Link2,
  List,
  Lock,
  LucideAngularModule,
  Mail,
  Map,
  MessageCircle,
  Minus,
  EllipsisVertical,
  PaintBucket,
  Pencil,
  Phone,
  Plug,
  Plus,
  Printer,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Signature,
  Share2,
  Sparkles,
  Star,
  Sun,
  Tag,
  Thermometer,
  Trash2,
  Trees,
  Truck,
  Upload,
  User,
  Users,
  Wifi,
  Wrench,
  X,
  Zap,
  AppWindow,
  Toolbox,
  Activity,
  RefreshCcw,
  KeyRound,
  Copy,
  AlertTriangle,
  Webhook,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { errorReportingInterceptor } from './core/interceptors/error-reporting.interceptor';
import { GlobalErrorHandler } from './core/handlers/global-error.handler';
import { TranslateLoader, provideTranslateService } from '@ngx-translate/core';
import { MultiTranslateHttpLoader } from 'ngx-translate-multi-http-loader';

registerLocaleData(localeNl);

const createTranslateLoader = (handler: HttpBackend) => new MultiTranslateHttpLoader(handler, [
  { prefix: '/assets/i18n/', suffix: '/common.json' },
  { prefix: '/assets/i18n/', suffix: '/navigation.json' },
  { prefix: '/assets/i18n/', suffix: '/auth.json' },
  { prefix: '/assets/i18n/', suffix: '/data-grid.json' },
  { prefix: '/assets/i18n/', suffix: '/sidebar.json' },
  { prefix: '/assets/i18n/', suffix: '/menu.json' },
  { prefix: '/assets/i18n/', suffix: '/profile.json' },
  { prefix: '/assets/i18n/', suffix: '/leads.json' },
  { prefix: '/assets/i18n/', suffix: '/services.json' },
  { prefix: '/assets/i18n/', suffix: '/offertes.json' },
  { prefix: '/assets/i18n/', suffix: '/catalog.json' },
  { prefix: '/assets/i18n/', suffix: '/partners.json' },
  { prefix: '/assets/i18n/', suffix: '/organization.json' },
  { prefix: '/assets/i18n/', suffix: '/appointments.json' },
  { prefix: '/assets/i18n/', suffix: '/webhook.json' },
  { prefix: '/assets/i18n/', suffix: '/google-ads.json' },
]);

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAnimations(),
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    { provide: LOCALE_ID, useValue: 'nl' },
    provideRouter(routes),
    provideHttpClient(withInterceptors([errorReportingInterceptor, authInterceptor])),
    provideTranslateService({
      loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpBackend],
      },
      fallbackLang: 'en',
      lang: 'nl'
    }),
    importProvidersFrom(
      ColorPickerModule,
      LucideAngularModule.pick({
        CircleAlert,
        ArrowLeft,
        ArrowLeftRight,
        BookOpen,
        Briefcase,
        Brush,
        Building,
        Calendar,
        CalendarCheck,
        Car,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronUp,
        Clock,
        Download,
        Droplet,
        Eraser,
        Eye,
        EyeOff,
        GripVertical,
        Globe,
        Hammer,
        HardHat,
        Heart,
        House,
        Image,
        Inbox,
        LayoutDashboard,
        Lightbulb,
        Link2,
        List,
        Lock,
        Mail,
        Map,
        MessageCircle,
        Minus,
        EllipsisVertical,
        PaintBucket,
        Pencil,
        Phone,
        Plug,
        Plus,
        Printer,
        Save,
        Scissors,
        Search,
        Send,
        Settings,
        Shield,
        ShieldCheck,
        Signature,
        Share2,
        Sparkles,
        Star,
        Sun,
        Tag,
        Thermometer,
        Trash2,
        Trees,
        Truck,
        User,
        Users,
        Wifi,
        RefreshCcw,
        AppWindow,
        Upload,
        Wrench,
        X,
        Zap,
        Flame,
        FileText,
        Toolbox,
        Activity,
        KeyRound,
        Copy,
        AlertTriangle,
        Webhook,
      }),
    ),
  ]
};
