import { ApplicationConfig, ErrorHandler, importProvidersFrom, LOCALE_ID, provideBrowserGlobalErrorListeners } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import localeNl from '@angular/common/locales/nl';
import { HttpBackend, provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { ColorPickerModule } from '@iplab/ngx-color-picker';
import {
  CircleAlert,
  Bell,
  ArrowDownLeft,
  ArrowLeft,
  ArrowUpRight,
  ArrowLeftRight,
  BookOpen,
  BrainCircuit,
  BookmarkPlus,
  Briefcase,
  Brush,
  Building,
  Calendar,
  CalendarCheck,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CloudCheck,
  Download,
  Droplet,
  Euro,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  Flame,
  FileText,
  GitBranch,
  GripVertical,
  Globe,
  Hammer,
  Hash,
  HardHat,
  Heart,
  House,
  Image,
  Info,
  Inbox,
  LayoutDashboard,
  Lightbulb,
  Link,
  Link2,
  List,
  Lock,
  LucideAngularModule,
  LoaderCircle,
  Mail,
  MailOpen,
  MailSearch,
  Map,
  MapPin,
  MessageCircle,
  MessageCircleOff,
  Minus,
  MoonStar,
  Layers,
  EllipsisVertical,
  Archive,
  PaintBucket,
  Paperclip,
  Percent,
  SquarePen,
  Pencil,
  Phone,
  Plug,
  Plus,
  Printer,
  Save,
  Scissors,
  Search,
  SearchX,
  RefreshCw,
  Radio,
  Reply,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Signature,
  Share2,
  Sparkles,
  Star,
  Sun,
  Tag,
  Thermometer,
  Trash2,
  Trees,
  Truck,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Wifi,
  Wrench,
  X,
  Zap,
  ListChecks,
  ListPlus,
  AppWindow,
  Toolbox,
  Activity,
  RefreshCcw,
  KeyRound,
  Copy,
  ContactRound,
  TriangleAlert,
  Webhook,
  TrendingUp,
  Handshake,
  MapPinned,
  MessageSquareText,
  Mic,
  Pin,
  SmilePlus,
  RotateCcw,
  Sticker,
  TextAlignStart,
  Undo2,
  Unlink2,
  ChartColumn,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { errorReportingInterceptor } from './core/interceptors/error-reporting.interceptor';
import { GlobalErrorHandler } from './core/handlers/global-error.handler';
import { TranslateLoader, provideTranslateService } from '@ngx-translate/core';
import { MultiTranslateHttpLoader } from 'ngx-translate-multi-http-loader';

registerLocaleData(localeNl);

const translationVersion = '__APP_BUILD_ID__';
const versionedTranslationSuffix = (fileName: string) => `${fileName}?v=${encodeURIComponent(translationVersion)}`;

const createTranslateLoader = (handler: HttpBackend) => new MultiTranslateHttpLoader(handler, [
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/common.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/navigation.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/auth.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/data-grid.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/sidebar.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/menu.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/profile.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/leads.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/services.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/offertes.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/catalog.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/partners.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/organization.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/appointments.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/webhook.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/google-ads.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/search.json') },
  { prefix: '/assets/i18n/', suffix: versionedTranslationSuffix('/tasks.json') },
]);

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    { provide: LOCALE_ID, useValue: 'nl' },
    provideRouter(routes),
    provideHttpClient(withInterceptors([errorReportingInterceptor, authInterceptor])),
    provideTranslateService({
      loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpBackend],
      },
      fallbackLang: 'en',
      lang: 'nl'
    }),
    importProvidersFrom(
      ColorPickerModule,
      LucideAngularModule.pick({
        CircleAlert,
        Bell,
        ArrowDownLeft,
        ArrowLeft,
        ArrowUpRight,
        ArrowLeftRight,
        BookOpen,
        BrainCircuit,
        BookmarkPlus,
        Briefcase,
        Brush,
        Building,
        Calendar,
        CalendarCheck,
        Car,
        Check,
        CheckCheck,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        Clock,
        CloudCheck,
        Download,
        Droplet,
        Euro,
        Eraser,
        ExternalLink,
        Eye,
        EyeOff,
        GripVertical,
        Globe,
        Hammer,
        Hash,
        HardHat,
        Heart,
        House,
        Image,
        Info,
        Inbox,
        LayoutDashboard,
        Lightbulb,
        Link,
        Link2,
        List,
        Lock,
        LoaderCircle,
        Unlink2,
        Mail,
        MailOpen,
        MailSearch,
        Map,
        MapPin,
        MessageCircle,
        MessageCircleOff,
        Minus,
        MoonStar,
        Layers,
        EllipsisVertical,
        Archive,
        PaintBucket,
        Paperclip,
        Percent,
        SquarePen,
        Pencil,
        Phone,
        Plug,
        Plus,
        Printer,
        Save,
        Scissors,
        Search,
        SearchX,
        RefreshCw,
        Radio,
        Reply,
        Send,
        Settings,
        Shield,
        ShieldCheck,
        Signature,
        Share2,
        Sparkles,
        Star,
        Sun,
        Tag,
        Thermometer,
        Trash2,
        Trees,
        Truck,
        User,
        UserCheck,
        UserPlus,
        Users,
        Video,
        Wifi,
        RefreshCcw,
        AppWindow,
        Upload,
        Wrench,
        X,
        Zap,
        ListChecks,
        ListPlus,
        Flame,
        FileText,
        GitBranch,
        Toolbox,
        Activity,
        KeyRound,
        Copy,
        ContactRound,
        TriangleAlert,
        Webhook,
        TrendingUp,
        Handshake,
        MapPinned,
        MessageSquareText,
        Mic,
        Pin,
        SmilePlus,
        RotateCcw,
        Sticker,
        TextAlignStart,
        Undo2,
        ChartColumn,
      }),
    ),
  ]
};
